### ISSUE TITLE
Separate encodings yaml file (strip out of schemas currently in the mbkranz/encodings branch)

### ISSUE THREAD

**Issue by mbkranz** [jcoin-maarc/JCOIN-Core-Measures#3]
Create field-wise encodings (e.g., 1=Male, 2=Female etc) to allow conversion to SPSS, Stata, etc

**Comment by mbkranz** [comment]
This work is currently on non-main branches but is under develepment in conjunction with reserve codes

**Comment by mbkranz** [comment]
The schema describes the csv file but the versions of the metadata-rich has encodings. We need to take encodings out of schema and put into yaml file. These will be used as part of the pipeline.

**Comment by mbkranz** [comment]
Make one file for all schemas in client measures

**Comment by pschumm** [comment]
Here is the file I started.

**Comment by mbkranz** [comment]
delete reserve codes from each field

**Comment by mbkranz** [comment]
Completed in 99fad16cfd15533830a15abf4a1c3448849bb877 and modified thereafter so closing
